### ISSUE TITLE
IoC Setup Required for Example Code?

### ISSUE THREAD

**Issue by brianmriley** [djfdyuruiry/ts-lambda-api#28]
First, this is a fantastic library. I come from a more container based Docker world and have built apps using `routing-controllers` and was hoping to find a similar solution / write my own for Lambdas -- you guys nailed it.

One question, are you required to setup the IoC container for all controllers when using the local testing library `ts-lambda-api-local`? I attempted to setup a quick test harness app with `ApiConsoleApp` from your accompanying lib, but without setting up the controller for DI the routing never worked. 

* Is this something missing from the docs or another part of the config I might have missed?
* Is the IoC config required for the actual run of the Lambda as well?

Again, great framework and keep up the good work.

**Comment by djfdyuruiry** [comment]
Thanks for the feedback, great to hear the library is helping you out! 

A controller currently must be decorated with `@injectable()` so that it can be built by `ts-lambda-api`. The framework uses the Inversify.JS library under the hood and this is what actually builds instances of discovered controllers; the `injectable` decorator allows injecting a type without having to explicitly register it with the IOC container.

In terms of Lambda vs. express, the behaviour will be the same. The local testing library is simply a wrapper around the same engine.

Do you think it would be useful to be able to disable dependency injection? (not something I have considered adding before)
